language: python
python: "3.7"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip install -r requirement.txt

# script to run tests. Script can have many commands, one per line.
script:
  - python manage.py test
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)